### ISSUE TITLE
Sector page titles showing font-awesome syntax instead of real page title

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#1]
Transportation works (see title of the tab)

But Land Sinks and other Sectors don't.

**Comment by bigolboyyo** [comment]
Love this concept! Need a couple days to finish up a project I'm working on, but then I'd love to connect and get some more details or maybe a walkthrough of your concept and ideas? 

wesgrant.dev@gmail.com

**Comment by futuresoup** [comment]
@bigolboyyo - amazing, just emailed you!  :D

Great personal website by the way.

**Comment by futuresoup** [comment]
Resolved by adding the offending pages as menu items in `mkdocs.yml`. More of a workaround. Good for now but restricts Page Titles from having icons in the H1 Header.
