### ISSUE TITLE
Options for a static site CMS

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#10]
We really need a CMS to collaborate with writers who can't figure out GitHub, Git, or raw Markdown workflows.

(I brought this up in the [Material for MKDocs forum](https://github.com/squidfunk/mkdocs-material/discussions/5498)).

[Decap CMS](https://decapcms.org/) is an open source CMS that should work great for MKDocs.

How could this be implemented?

If it's too hard or not possible, we could try to be creative.

For example, authoring in Notion and using their API? Some sort of notebook environment? The GitHub GUI?

**Comment by alexmayberry** [comment]
I'll take a look at Decap and see what it will take.

**Comment by alexmayberry** [comment]
#13 allows users to update the page body of md files and attributes like title and tags for pages with frontmatter sectiions.

**Comment by futuresoup** [comment]
@alexmayberry let's mess with the Netlify stuff today and we should be good!

**Comment by alexmayberry** [comment]
Looks like we are currently using this template for page front matters:
```md/yaml
---
title: 
description:
authors:
  - 
date: 
tags:
  -
  -
---
```

I think we should add attributes for landing image filename, image URL, image caption etc

**Comment by alexmayberry** [comment]
The CMS is live on prod and those who have been invited can login (we are limited to 5 CMS users but we can also open it to anyone and add our own auth). But it looks like I didn't quite get the permissions write for my github OAuth token as users get this error when saving changes

![Screenshot from 2023-05-23 17-14-06](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/51015213/1783f101-1433-4816-999b-bccce4559034)
.

**Comment by alexmayberry** [comment]
Added a new read/write person access token and we're live! [this page](https://www.climatetechhandbook.com/afresh/) now includes text added via the CMS. Login at https://climatetechhandbook.com/admin. 

We still have lots of bugs to fix and improvements to make, but it's usable.

**Comment by futuresoup** [comment]
@alexmayberry  I'll need to break this down into separate Issues.

4 things that need to happen asap to get this to the MVP state.
1. Fix the { in the file name
2. Get the PRs from GitHub in the person’s name who’s making the edits. Currently it’s all under Alex Mayberry
3. Get the permissions hierarchy put in place. I think anybody can currently publish and merge PRs into Main
4. Initiate a mass update through the backend Flask system to get the front matter formatted so the pages work in the CMS

Amazing progress though! :D

**Comment by Semiotikal** [comment]
> We really need a CMS to collaborate with writers who can't figure out GitHub, Git, or raw Markdown workflows.
> 
> (I brought this up in the [Material for MKDocs forum](https://github.com/squidfunk/mkdocs-material/discussions/5498)).
> 
> [Decap CMS](https://decapcms.org/) is an open source CMS that should work great for MKDocs.
> 
> How could this be implemented?
> 
> If it's too hard or not possible, we could try to be creative.
> 
> For example, authoring in Notion and using their API? Some sort of notebook environment? The GitHub GUI?

hey, i came across this from another post you made saying you were using mkdocs + decap CMS. Did it work? I noticed also you recently migrated to docusaurus, any specific reasons why over material for mkdocs?. I'm interested in using decap cms but i really like mkdocs as well.

**Comment by futuresoup** [comment]
@Semiotikal thanks for writing! See my comment in the MKDocs Discussion post that you mentioned me in.

Decap works fine on both and is just as easy to install if I recall correctly.
