### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by UlianaBil** [climate-tech-handbook/climate-tech-handbook#101]
Developers, please fix those links, whenever you have time.  Because it directly affects the SEO rankings of the website

<img width="1117" alt="Screenshot 2023-06-05 at 2 23 41 PM" src="https://github.com/climate-tech-handbook/climate-tech-handbook/assets/121840724/33524719-8096-4136-9d8f-d5ae3899e3cc">

**Comment by futuresoup** [comment]
Thanks so much for filing this @UlianaBil! Can you post the links to the page I can't tell what pages they are on from your screenshot

**Comment by UlianaBil** [comment]
@futuresoup you should be able to open those links from this PDF by pressing url
[broken links.pdf](https://github.com/climate-tech-handbook/climate-tech-handbook/files/11659406/broken.links.pdf)

**Comment by futuresoup** [comment]
Fixed! We passed with 0 broken links now!

Thank you so so much for bringing this to our attention.

![Image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/1459051/b9b5ca59-0372-435c-8091-1fd4698673bb)
