### ISSUE TITLE
Add Docusaurus WIP repo

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#138]
It's just about ready - [here is @bigolboyyo's personal repo](https://github.com/bigolboyyo/docusaurus-cth-wg) that needs to be moved

just needs a dev review from @shreeup @connor-cs @airbr 

## To Do

- [ ] Someone please claim this in a comment below for Friday release @shreeup @connor-cs @airbr 

- [ ] Add notice in README that it's not the live website, but a testing site for our migration available at [docusaurus.climatetechhandbook.com](https://docusaurus.climatetechhandbook.com/) (Password: **test**)

- [ ] Ensure it runs locally and README makes sense for new dev contributors

- [ ] _**Anything I'm missing?**_

**Comment by bigolboyyo** [comment]
Updated with disclaimer and transferred ownership. Please feel free to still proofread and make suggestions and changes.

https://github.com/climate-tech-handbook/docusaurus-cth
