### ISSUE TITLE
Add docusaurus search

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#165]
Hoping for another option besides Algolia. I'm a bit confused about the [options](https://docusaurus.io/docs/search).

**Comment by benj1r** [comment]
if our content on the site is small enough the simplest option just seems to be to use the [local search](https://docusaurus.io/docs/search#using-local-search) option.

if you're wanting to use something specifically that isnt Algolia, their other listed option is self-hosted [Typesense](https://docusaurus.io/docs/search#using-typesense-docsearch) search bar.
