### ISSUE TITLE
Climate Clock | Research and/or styling

### ISSUE THREAD

**Issue by bigolboyyo** [climate-tech-handbook/climate-tech-handbook#37]
So currently we are using a widget from [clock](climateclock.world) and it has default styling:
![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/031dfcc7-699e-444c-be9d-2411d90821fa)

We really only want the top Deadline bar. We don't need it to be red/black either.

I propose starting off with some basic styling. Make it fit into the home page better. Consider putting it at the top of the page. Or working with anyone associated with the layout issue: https://github.com/climate-tech-handbook/climate-tech-handbook/issues/30

My second thought is start doing research on a custom climate clock. Start off by gathering resources we could use, ie Nasa API, weather api, etc. Prototyping out a basic design or even pseudo code out the logic. This issue is meant to be a starting point for brainstorming as well.

Maybe work this into a custom weather widget that shows average increase in comparison with carbon output year after year (just an idea), feel free to be creative and shoot a stream of consciousness at this one.

The climate clock will be our main "call to action" on our homepage. The "why" it matters you join the movement today!

**Comment by futuresoup** [comment]
@connor-cs @ArLough  For now I say we style what I put from climateclock.net in the branch `homepage-clock-alternative`

**Comment by bigolboyyo** [comment]
@futuresoup the current widget allows full customization of it's components and from what I could tell was more up to date than the other one!

**Comment by futuresoup** [comment]
@connor-cs @ArLough - do you guys want to try styling the clock on the `homepage-clock-alternative` branch?

That's something simple you can do now to make the current homepage look better

I'm attaching the design mockup.

In addition, let's see how it looks to put a small section below the larger main timer for the two other counters:
- Degress warming
- Tons of CO2

**Comment by bigolboyyo** [comment]
I've got a basic climate clock react component started. This is a definite workaround for the script I found.

@connor-cs and I found a [climate clock api](https://docs.climateclock.world/climate-clock-docs/climate-clock-api) and it should make developing our own custom climate clock logic super easy!

Here's the component at it's current state for insight.
```
import React, { useEffect, useCallback, useState, useRef } from "react";
import clsx from "clsx";
import styles from "./ClimateClock.module.css";
import { loadScripts, scriptCleanup } from "@site/src/utils/scriptLogic";

interface ClockConfig {
  scriptType?: string;
  originUrl?: string;
  scriptTags?: string[];
}

const ClimateClock: React.FC<ClockConfig> = ({
  scriptType = "text/javascript",
  originUrl = "https://climateclock.net/wp-content/themes/C2D/js/",
  scriptTags = [
    `${originUrl}jquery.min.js`,
    `${originUrl}jquery.isMobile.min.js`,
    `${originUrl}magnific-popup.min.js`,
    `${originUrl}CO2Calculator.js?r=202111041017&ver=4.7.26`,
    `${originUrl}scripts.js?r=202111041017&ver=4.7.26`,
  ],
}) => {
  const countdownRef = useRef<HTMLDivElement>(null);
  const [countdown, setCountdown] = useState<string | null>(null);

  const loadClimateClockScripts = useCallback(() => {
    loadScripts(scriptTags);
    return () => {
      scriptCleanup(scriptTags);
    };
  }, [originUrl, scriptType, scriptTags]);

  useEffect(() => {
    const cleanup = loadClimateClockScripts();

    if (countdownRef.current) {
      const observer = new MutationObserver((mutationsList) => {
        for (const mutation of mutationsList) {
          if (
            mutation.type === "childList" &&
            mutation.target === countdownRef.current
          ) {
            const countdownValue = countdownRef.current.textContent;
            setCountdown(countdownValue);
          }
        }
      });

      observer.observe(countdownRef.current, { childList: true });

      return () => {
        observer.disconnect();
      };
    }

    return cleanup;
  }, [loadClimateClockScripts]);

  return (
    <div id="clock" className={clsx(styles.clock)}>
      <div className={clsx(styles.countdown)}>
        <h3 id="time-to-two">Time Left To Limit Global Warming To 1.5ºC</h3>
        <div
          id="timecountdown"
          ref={countdownRef}
          style={{ display: "none" }}
        ></div>
        <span>{countdown}</span>
      </div>
    </div>
  );
};

export default ClimateClock;
```
