### ISSUE TITLE
Get Podcast Pagination working

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#408]

**Comment by futuresoup** [comment]
@Danlinlin @purplecarrot625 - can you set up the podcast pagination code in the /component-library page so we can use it in the handbook?

I can't remember how the code works 🥺

**Comment by Danlinlin** [comment]
@futuresoup The current situation is that the code could run locally, but an error occurred when it was built on Netify. I'm trying to figure it out and seek help from Docusaurus discord community. 
I linked the PR to this issue.  If you wanna try the pagination, you could use the updated code in that commit and run it on your local machine.

**Comment by futuresoup** [comment]
Oh I see, thank you for the update @Danlinlin!

Let's take a break from getting pagination to work and focus on another goal. I think there are more pressing needs.
