### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#424]
We need a way for images to have a nice caption formatting so writers can put in image captions using markdown syntax.

We'll be using @bl912 's design. The one with the right alignment

![Image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/1459051/650e7f90-fe93-40b6-a0ec-5bfe568ee7e9)

In HTML this is accomplished using the following syntax:

```
<figure>
    <img src="image-url.jpg" alt="Alt text" />
    <figcaption>This is the image caption</figcaption>
</figure>
```

However, this is cumbersome. It would be better if we supported a simple Markdown syntax that replicate's Pandoc's format, which I believe is:

`![alt text](image-url.jpg "This is the image caption")`

According to phind.com this is the method:

1. Create a Custom Remark Plugin

You'll need to create a custom Remark plugin that recognizes your image caption syntax and transforms it into the <figure> and <figcaption> HTML structure. This involves parsing the Markdown content to find instances of your syntax and then replacing them with the desired HTML.
2. Register the Plugin with Docusaurus

Once your plugin is created, you'll need to register it with Docusaurus so that it's used during the Markdown processing. This can be done by adding the plugin to the `remarkPlugins` array in your `docusaurus.config.js` file.

Example Plugin Implementation:

```
// customImageCaptionPlugin.js
const visit = require('unist-util-visit');

module.exports = function customImageCaptionPlugin() {
 return (tree) => {
    visit(tree, 'image', (node) => {
      // Check if the node has a title (caption)
      if (node.title) {
        // Create a new figure node
        const figure = {
          type: 'figure',
          children: [
            node, // The original image node
            {
              type: 'figcaption',
              children: [{ type: 'text', value: node.title }],
            },
          ],
        };

        // Replace the image node with the figure node
        node.type = 'figure';
        node.children = [figure];
      }
    });
 };
};

```

Below is a simplified example of what the plugin might look like. This example assumes you're familiar with creating Remark plugins and might need adjustments based on your specific requirements.

```
// docusaurus.config.js
module.exports = {
 presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          remarkPlugins: [require('./path/to/customImageCaptionPlugin')],
        },
      },
    ],
 ],
};
```

**Comment by VitaRox** [comment]
I'm curious about this issue. Is it that a) an ImageCaption component needs to be made, so it can be reused for other image captions, or b) the images just need someone to write captions describing them (like hard-coded)? @futuresoup

**Comment by futuresoup** [comment]
@VitaRox we're hoping to make it a docusaurus plugin using ReMark with the markdown syntax. I'm still learning about how this would work quite frankly.

We would love your help but I know you've been busy

**Comment by MyBaBB** [comment]
I believe that I have the component correct,  I would like to collaborate with @Sugam Goel to see if we can iron this out in the docusaurus.config file

**Comment by MyBaBB** [comment]
# I think that we are just way over thinking this. And all the added will only cause an issue somewhere. 
   
#### We are trying to do this. 
* ` ![That Image](/img/.jpg "figcaption here") `
#### When all we have to do is just this 
* ` ![That Image](/img/.jpg) ` 
* Next Line - Figcaption Words

#### While this is what is achieved naturally here.
* ` ![That Image](/img/.jpg  "Tooltip here") `

#### Or we could have both by typing this
* ` ![That Image](/img/.jpg  "Tooltip here") `
* Next Line - Figcaption words

 ### Conclusion. Just start a new line and write the figcaption in.

**Comment by Sugamgoel28** [comment]
Is this relevant?
https://github.com/facebook/docusaurus/discussions/4633

**Comment by futuresoup** [comment]
@Sugamgoel28 @MyBaBB - yes it looks like the right direction. Do you understand what they're saying about passing remark/rehype plugins so we can invent our own syntax?

[The implementation example](https://github.com/facebook/docusaurus/discussions/4633#discussioncomment-622592) provided from @cmdcolin seems relevant.

The only issue with the way he did it is that:

A) it requires importing the component on each page which is cumbersome and not good for writers. I also don't know if it will be work out of the box with our Decap CMS system

B) The syntax does not look like markdown, it looks like jsx. That's more of a minor thing, but it is easy to forget the syntax the way he has it and perhaps incompatible with migrating to different systems if we decide to move away from Docusaurus.

That said, you're welcome to try his implementation as a backup if we can't make an official plugin that does this the proper way.
