### ISSUE TITLE
Incorrect information showing on the Countdown Counter before loading correct info

### ISSUE THREAD

**Issue by airbr** [climate-tech-handbook/climate-tech-handbook#430]
Currently for me on Google Chrome it shows a O and then NaN in the fields of the website. This creates a not optimal loading experience of the web page. 

Here isa. WebPageTest Video showing this in action:
![handbook](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/18056682/81e66466-28e2-4dd6-af7b-1fdad35967b6)

This could likely be fixed by hiding the counter until the JS runs needed to show it.

**Comment by MyBaBB** [comment]
The Clock isn't working properly on Firefox,   I fixed the issue before but I just noticed that it was still giving the NAN on the clock.    I have the solution.
