### ISSUE TITLE
Background on mobile changes from grey to white, make breakpoint CSS fix

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#442]

**Comment by MyBaBB** [comment]
Hi,  I would like to get involved in the project, If you would assign me this task I will work on it for you.    Thanks.

**Comment by futuresoup** [comment]
@MyBaBB - hey Brett I'd love to collaborate! Sorry I missed your message...

Can I follow up with you on Slack? - join here https://chat.climatetechhandbook.com

**Comment by MyBaBB** [comment]
Hi, thanks for responding back to me,  However after reviewing your code I
realized that it is written in TSX and I am writing JSX. Although I could
figure it out, I would not be efficient in this language.    I can do the
css with no problem.  Or I could convert it.   TSX would be my next
language to learn so I will this and follow you until I get faster at
writing TSX.   Thank you.

**Comment by MyBaBB** [comment]
ok, Me and Mike Watton have connected.
