### ISSUE TITLE
Make table of contents accessible on mobile

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#9]
The table of contents only displays on Desktop.

For better mobile usability, it should also be accessible via flyout from an icon on the top right header bar.

You can see an [example](https://gpt-index.readthedocs.io/en/latest/index.html) with the "Read the Docs" layout.

Make the window responsive and look at the top right.

**Comment by bigolboyyo** [comment]
Alright so a media query should fix this with a little custom js and css. Then I'll work on adding the drawer and onClick functionality for the toc menu

`max-width: 959px`
![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/a3901f5b-c470-4633-bc30-2d25a4d97491)

vs

`max-width: 960px`
![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/d4039a83-f008-4958-ad94-0db52a5ab535)

**Comment by bigolboyyo** [comment]
We have liftoff! Need to implement drawer and nav functionality for it.

Also the second hamburger icon on the other side is kind of gross imo. Maybe someone has an idea for a better icon? @futuresoup 

![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/8ce52f1b-d06d-49da-b034-ecb5550ab9e5)

**Comment by bigolboyyo** [comment]
Wiki made for anyone who wants more insight: https://github.com/climate-tech-handbook/climate-tech-handbook/wiki/Customizing-MKDocs

Drawer is 95% of the way done outside of a minor bug I should have sorted in the next day or two.

![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/1f3dc48a-c7c5-406f-aa34-c1e97c03f899)

---

## BUG DETAILS

When programmatically navigating forward with `<a>` tags the `{{page.toc}}` updates normally with a popState() event. I was able to workaround most of the missed updates using a simple `location.reload()` cheat. (This obviously isn't optimal, but for a static text based site it shouldn't cause issues)

So for example If you reference the image above and I click the main Climate Tech Handbook title it would not update the new table of contents for the page unless you refreshed first, this is where my cheat comes in.

![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/8ab40c68-cc74-4342-97fe-9d1e682db2d9)

I went home and the {{page.toc}} updates with my `tocDrawer.js` script.

This workaround doesn't cover everything yet and here is what happens (it keeps the memory of the last updated `{{page.toc}}`)

Clicking anything in the right side drawer doesn't update our `{{page.toc}}`

![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/e38425f9-0a8e-4b13-841c-b37cae450e80)

The `<a>` tag here uses `href=[".."]` so I thought adding all of the relative paths to my script and rediverting to the home page with a forced reload would work. But a `popState()` event doesn't occur. 

So figuring out what event is occurring and how to mitigate would be our fastest fix.

Best fix is to figure out how to control the update to `{{page.toc}}`

![image](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/95878821/412f4c3c-73a4-4f13-9c3e-4371a85a0d2e)

**Comment by bigolboyyo** [comment]
After looking more at meta tags I think I have a better approach.

We can create tags for each page's table of contents(TOC) and store them in the [Front Matter](https://starfallprojects.github.io/mkdocs-macros-yaml-examples/frontmatter/)

And then just load that for each page's drawer. I believe this will prevent the need for unnecessary page refreshes.

Something similar to this
```
tocTags: 
  - Welcome
  - Join the Movement
  - Nav 3
  - ... so on
```

**Comment by bigolboyyo** [comment]
[page-toc](https://github.com/climate-tech-handbook/climate-tech-handbook/tree/page-toc) branch pushed to the handbook repo.

@futuresoup @alexmayberry @ArLough @connor-cs 

Check it out and tell me what you think

If someone could tag Uliana too please!

**Comment by futuresoup** [comment]
@ArLough do you want to review and test Wes's code

**Comment by ArLough** [comment]
Sure, I'll take a look 👍🏻

**Comment by ArLough** [comment]
@bigolboyyo Overall it looks good to me!

The only thing would be I feel like the left padding on the table of contents header and the items are a bit too small and it might be good to add some more. But, I'm open if people have other opinions on this

**Comment by futuresoup** [comment]
Found some bugs and determined that this will be on hold until we migrate to Docusaurus or Starlight

**Comment by futuresoup** [comment]
@mzhanggg how is this going? Are you taking a break with the project?

@dovid11564 is also happy to pick it up if you're too busy?

**Comment by futuresoup** [comment]
Holy crap we did it! So great!!! 🎉
